# This file was generated by GoReleaser. DO NOT EDIT.
cask "incorpus" do
  version "0.29.0"

  on_macos do
    on_arm do
      sha256 "5aa2037e546771a21884c34e7797428658508c1172ecf4dbfa0ac7334c750c86"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "ad6b4c89fb25e646d3bdf2d21207b71d9915dab8e31cf2e8a1f4d225defadeac"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "97889991f1c2f1ed1e1c66f0d32997c5e577fdfa5fab519355db4ee356d23288"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5d548d6162bcdc0c52e9954bba20c0fcf31e71748c4d6af1a7fcf7a283ba1f81"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "incorpus"
  desc "Agentic CLI for the Incorpus business management platform"
  homepage "https://incorpus.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "incorpus"

  # No zap stanza required
end
