# This file was generated by GoReleaser. DO NOT EDIT.
cask "incorpus" do
  version "0.30.0"

  on_macos do
    on_arm do
      sha256 "a311ef8220fc3bb2da6684b3108c7f414bce36cc877dcf47140d4861348bf0ff"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_arm64.tar.gz"
    end
    on_intel do
      sha256 "6200a7480608a737fd806009d6b529254c681877cde739f3873c67025ad2eaf9"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "240e0c9d1065b2f4801b5fe02a821184fef54250d075185cedaef4cc572fece1"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "deacf088fae89bb7d9287bf9d1c2a32a9d7c8f1724e576f42cce67118d8c06d9"
      url "https://github.com/srank-org/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "incorpus"
  desc "Agentic CLI for the Incorpus business management platform"
  homepage "https://incorpus.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "incorpus"

  # No zap stanza required
end
