# This file was generated by GoReleaser. DO NOT EDIT.
cask "incorpus" do
  version "0.26.0"

  on_macos do
    on_intel do
      sha256 "cc2416ab37da7102ef4208da748110c09109a6221e343783d674f1acb9cc0fe4"
      url "https://github.com/srank-inc/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fb08a7f4cf027e148961208082250a76927e960f649290f5e96d83774dddf0cc"
      url "https://github.com/srank-inc/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f1d64740b9374d23aeea2b0fcc6ed35a1a4161d38ebda2328c53215666faffbb"
      url "https://github.com/srank-inc/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3755fc6c948ec032e0c6d25f45d1e062bdf0cfa7dc25e390d8a88d960e7dee60"
      url "https://github.com/srank-inc/incorpus-cli/releases/download/v#{version}/incorpus_#{version}_linux_arm64.tar.gz"
    end
  end

  name "incorpus"
  desc "Agentic CLI for the Incorpus business management platform"
  homepage "https://incorpus.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "incorpus"

  # No zap stanza required

end
